# Generated by Django 2.1 on 2018-08-30 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lp_auth', '0002_auto_20180830_0618'),
        ('courses', '0002_student_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'course')},
        ),
    ]
