# Generated by Django 2.1 on 2018-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0003_auto_20180830_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
