# Generated by Django 2.1 on 2018-09-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lp_auth', '0002_auto_20180830_0618'),
        ('courses', '0004_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, unique=True)),
                ('sentence', models.CharField(max_length=1000, null=True)),
                ('definition', models.CharField(max_length=1000, null=True)),
                ('sound_path', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateCard',
            fields=[
                ('card_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='courses.Card')),
            ],
            options={
                'managed': False,
            },
            bases=('courses.card',),
        ),
        migrations.AddField(
            model_name='card',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lp_auth.User'),
        ),
    ]
