# Generated by Django 2.1 on 2018-09-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0005_auto_20180901_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='translation',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
